### ISSUE TITLE
Upgrade Repo to newer Version

### ISSUE THREAD

**Issue by cycl0ne** [GuillaumeDesforges/pixijs-typescript-starter#41]
If you use this boilerplate in 2024, it wont work. WebPack is using an outdated SSL function. Upgrading the components to a newer version breaks the whole build.

**Comment by GuillaumeDesforges** [comment]
Thanks, sure this repo is 2 years old (which is an eternity in JS world :smile: ).
Would you like to upgrade it? I'm not interested in doing it, so if nobody picks it up I may just archive the repo as well. :slightly_smiling_face:

**Comment by cycl0ne** [comment]
Archive it.. there is someone who created already a newer one:

https://github.com/yordan-kanchelov/pixi-typescript-boilerplate

**Comment by GuillaumeDesforges** [comment]
Nice! I'll redirect people to it as well. Cheers.
