### ISSUE TITLE
pwa-node-terminal not recognized

### ISSUE THREAD

**Issue by RobbeRamon** [GuillaumeDesforges/pixijs-typescript-starter#8]
I want to start using the delivered configuration, but I get the error that pwa-node-terminal is not supported.
I do have the javascript debugger package installed in my vscode.
Can you help me with this?
Thank you!

![image](https://i.imgur.com/dLqrkIE.png)

**Comment by GuillaumeDesforges** [comment]
Hi @RobbeRamon

The pwa- prefix was a way to target VS Code's "new" JavaScript debugger, which at the time was named vscode-pwa.
Have you tried to install pwa-node-terminal extension as suggested by the dialog you are having?

Note that the project is now 1 year old, so it might need some modifications. I'll try to look into it when I can, but if you find a fix to your issue please share your findings :)

**Comment by darkoverlordofdata** [comment]
see [https://github.com/microsoft/vscode/issues/99307](https://github.com/microsoft/vscode/issues/99307).
in the launch.json, change

            "type": "pwa-node-terminal",

to

            "type": "node-terminal",

**Comment by GuillaumeDesforges** [comment]
Thanks @darkoverlordofdata, that's what I thought. I hadn't have the time to do it yet, will do it soon.

**Comment by GuillaumeDesforges** [comment]
Fixed and tested, thanks for the report @RobbeRamon
